using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;
using System.Threading.Tasks;
using Neko.Drawing;

namespace Neko.Sources.APIS;

public class DogCEO : IImageSource
{
    public class Config : IImageConfig
    {
        public bool enabled;
        public Breed breed = Breed.all;
        public int selected;

        public IImageSource? LoadConfig() => enabled ? new DogCEO(breed) : null;
    }

    public bool Faulted { get; set; }

    private const int URL_COUNT = 10; // max 50
    private readonly MultiURLs<DogCEOJson> URLs;
    private readonly Breed breed;

    public DogCEO(Breed b)
    {
        breed = b;
        URLs = b == Breed.all
            ? (new($"https://dog.ceo/api/breeds/image/random/{URL_COUNT}", this))
            : (new($"https://dog.ceo/api/breed/{BreedPath(b)}/images/random/{URL_COUNT}", this));
    }
    public NekoImage Next(CancellationToken ct = default)
    {
        return new NekoImage(async (_) =>
        {
            var url = await URLs.GetURL(ct);
            return await Download.DownloadImage(url, typeof(DogCEO), ct);
        });
    }

    public string Name => "Dog CEO";

    public override string ToString()
    {
        var breed = Plugin.Config.Sources.DogCEO.breed;
        return $"Dog CEO\tBreed: {BreedName(breed)}\t{URLs}";
    }

    public static string BreedName(Breed b)
    {
        var textInfo = new CultureInfo("en-US", false).TextInfo;
        var name = Enum.GetName(typeof(Breed), b)?.Trim() ?? "Unknown";
        name = name.Replace("_", " (");
        if (name.Contains('('))
            name += ")";
        return textInfo.ToTitleCase(name);
    }

    public static string BreedPath(Breed b)
    {
        var name = Enum.GetName(typeof(Breed), b)?.Trim() ?? "Unknown";
        return name.Replace("_", "/");
    }

    public bool Equals(IImageSource? other) => other != null && other is DogCEO d && d.breed == breed;

#pragma warning disable
    public class DogCEOJson : IJsonToList<string>
    {
        public List<string> message { get; set; }
        public string status { get; set; }

        public List<string> ToList() => message;
    }
    public enum Breed
    {
        all,
        affenpinscher, african, airedale, akita, appenzeller,
        australian_shepherd,
        basenji, beagle, bluetick, borzoi, bouvier, boxer, brabancon, briard, buhund_norwegian,
        bulldog, bulldog_boston, bulldog_english, bulldog_french,
        bullterrier, bullterrier_staffordshire,
        cattledog_australian,
        chihuahua, chow, clumber, cockapoo,
        collie, collie_border,
        coonhound,
        corgi, corgi_cardigan,
        cotondetulear, dachshund, dalmatian,
        dane,
        deerhound_scottish,
        dhole, dingo, doberman,
        elkhound,
        entlebucher, eskimo,
        finnish_lapphund,
        frise_bichon,
        germanshepherd,
        greyhound, greyhound_italian,
        groenendael, havanese,
        hound, hound_afghan, hound_basset, hound_blood, hound_english, hound_ibizan, hound_plott, hound_walker,
        husky,
        keeshond, kelpie, komondor, kuvasz,
        labradoodle, labrador, leonberg, lhasa,
        malamute, malinois, maltese,
        mastiff, mastiff_bull, mastiff_english, mastiff_tibetan,
        mexicanhairless, mix,
        mountain, mountain_bernese, mountain_swiss,
        newfoundland, otterhound,
        ovcharka_caucasian,
        papillon, pekinese, pembroke,
        pinscher_miniature,
        pitbull,
        pointer, pointer_german, pointer_germanlonghair,
        pomeranian,
        poodle, poodle_medium, poodle_miniature, poodle_standard, poodle_toy,
        pug, puggle, pyrenees, redbone,
        retriever, retriever_chesapeake, retriever_curly, retriever_flatcoated, retriever_golden,
        ridgeback_rhodesian,
        rottweiler,
        saluki, samoyed, schipperke,
        schnauzer, schnauzer_giant, schnauzer_miniature,
        setter, setter_english, setter_gordon, setter_irish,
        sharpei,
        sheepdog, sheepdog_english, sheepdog_shetland,
        shiba, shihtzu,
        spaniel, spaniel_blenheim, spaniel_brittany, spaniel_cocker, spaniel_irish, spaniel_japanese, spaniel_sussex, spaniel_welsh,
        springer, springer_english,
        stbernard,
        terrier, terrier_american, terrier_australian, terrier_bedlington, terrier_border, terrier_cairn, terrier_dandie, terrier_fox,
        terrier_irish, terrier_kerryblue, terrier_lakeland, terrier_norfolk, terrier_norwich, terrier_patterdale, terrier_russell, terrier_scottish,
        terrier_sealyham, terrier_silky, terrier_tibetan, terrier_toy, terrier_welsh, terrier_westhighland, terrier_wheaten, terrier_yorkshire,
        tervuren,
        vizsla,
        waterdog, waterdog_spanish,
        weimaraner,
        whippet,
        wolfhound, wolfhound_irish,
    }

    public struct BreedInfo
    {
        public string Description;

        public BreedInfo(string desc)
        {
            Description = desc;
        }
    }

    public static readonly Dictionary<Breed, BreedInfo> BreedDictionary = new() {
        {Breed.affenpinscher,               new BreedInfo("Loyal, curious, and famously amusing, this almost-human toy dog is fearless out of all proportion to his size. As with all great comedians, it's the Affenpinscher's apparent seriousness of purpose that makes his antics all the more amusing.\n The Affen's apish look has been described many ways. They've been called 'monkey dogs' and 'ape terriers.' The French say diablotin moustachu ('mustached little devil'), and Star Wars fans argue whether they look more like Wookies or Ewoks.")},
        {Breed.african,                     new BreedInfo("The African wild dog (Lycaon pictus), also called the African painted dog and the African hunting dog, is a wild canine which is a native species to sub-Saharan Africa. It is the largest wild canine in Africa, and the only extant member of the genus Lycaon, which is distinguished from Canis by dentition highly specialised for a hypercarnivorous diet, and by a lack of dewclaws.")},
        {Breed.airedale,                    new BreedInfo("His size, strength, and unflagging spirit have earned the Airedale Terrier the nickname 'The King of Terriers'. The Airedale stands among the world's most versatile dog breeds and has distinguished himself as hunter, athlete, and companion.")},
        {Breed.akita,                       new BreedInfo("The Akita is a muscular, double-coated dog of ancient Japanese lineage famous for their dignity, courage, and loyalty. In their native land, they're venerated as family protectors and symbols of good health, happiness, and long life.")},
        {Breed.appenzeller,                 new BreedInfo("Loyal, curious, and famously amusing, this almost-human toy dog is fearless out of all proportion to his size. As with all great comedians, it's the Affenpinscher's apparent seriousness of purpose that makes his antics all the more amusing.")},
        {Breed.australian_shepherd,         new BreedInfo("The Australian Shepherd, a lean, tough ranch dog, is one of those 'only in America' stories: a European breed perfected in California by way of Australia. Fixtures on the rodeo circuit, they are closely associated with the cowboy life. The Australian Shepherd, the cowboy's herding dog of choice, is a medium-sized worker with a keen, penetrating gaze in the eye. Aussie coats offer different looks, including merle (a mottled pattern with contrasting shades of blue or red).")},
        {Breed.basenji,                     new BreedInfo("The Basenji, Africa's 'Barkless Dog' is a compact, sweet-faced hunter of intelligence and poise. They are unique and beguiling pets, best for owners who can meet their exercise needs and the challenge of training this catlike canine. Basenjis are small, graceful hounds standing 16 or 17 inches at the shoulder.")},
        {Breed.beagle,                      new BreedInfo("Not only is the Beagle an excellent hunting dog and loyal companion, it is also happy-go-lucky, funny, and thanks to its pleading expression cute. They were bred to hunt in packs, so they enjoy company and are generally easygoing. There are two Beagle varieties: those standing under 13 inches at the shoulder, and those between 13 and 15 inches. Both varieties are sturdy, solid, and 'big for their inches' as dog folks say. They come in such pleasing colors as lemon, red and white, and tricolor. ")},
        {Breed.bluetick,                    new BreedInfo("The sleekly beautiful Bluetick Coonhound is a sweet and affectionate charmer who might enjoy snoozing in the shade, but in pursuit of quarry he is relentless, bold, and single-minded. His off-the-charts prey drive must be channeled. Blueticks are speedy and compact nocturnal hunters named for the mottled (or 'ticked') black-and-blue pattern of the glossy coat. A large male can top out at 27 inches and 80 pounds; females are smaller.")},
        {Breed.borzoi,                      new BreedInfo("Among the most impressively beautiful of all dogs, the aristocratic Borzoi is cherished for his calm, agreeable temperament. In full stride, he is a princely package of strength, grace, and glamour flying by at 35 to 40 miles per hour. Borzoi are large, elegant sighthounds. A mature male stands at least 28 inches at the shoulder and weighs 75 to 105 pounds. Females will be smaller.")},
        {Breed.bouvier,                     new BreedInfo("They don't build 'em like this anymore. Burly and barrel-chested, the tousle-coated dog of Flandres is from a time and place where a dog had to work like well, a dog. These smart and steady all-purpose workers make excellent watchdogs. Standing as high as 27.5 inches, with heavy bone and powerful muscles beneath a weatherproof coat, and an impressive head accented by beard and mustache, Bouviers can do anything that needs doing in a barnyard or pasture except milk the cows.")},
        {Breed.boxer,                       new BreedInfo("Loyalty, affection, intelligence, work ethic, and good looks: Boxers are the whole doggy package. Bright and alert, sometimes silly, but always courageous, the Boxer has been among America's most popular dog breeds for a very long time. A well-made Boxer in peak condition is an awesome sight. A male can stand as high as 25 inches at the shoulder; females run smaller. Their muscles ripple beneath a short, tight-fitting coat.")},
        {Breed.brabancon,                   new BreedInfo("The Petit Brabancon is one variety of the Brussels Griffon breeds. The Brussels Griffons were originally bred and developed in the nineteenth century from the Smousje, a small ratting dog found throughout Belgium. These dogs were used to catch rodents in Belgian homes and stables, earning them the nickname of Griffon d'Ecurie, or Stable Griffon. Originally, they were larger than the dogs we see today. Although these little dogs had been around the area of Belgium for centuries, their ancestry also included that of the Affenpinscher.")},
        {Breed.briard,                      new BreedInfo("The Briard packs so much loyalty, love, and spirit into its ample frame that it's often described as a 'heart wrapped in fur.' The dashing good looks of these muscular Frenchmen radiate a distinct aura of Gallic romance and elegance. Briards are herders known for a wavy coat of either gray, tawny, or black, and an impressive head topped by a peek-a-boo hairdo parted naturally in the middle.")},
        {Breed.buhund_norwegian,            new BreedInfo("The densely coated Nowegian Buhund, a Nordic spitz-type closely associated with the Vikings, is a medium-sized cold-weather worker adept at herding and guarding. As family dogs, Buhunds are smart, affectionate, and steadfastly devoted. The Buhund, a prototypical spitz, provides a good opportunity to explain the term. Spitz are cold-weather breeds characterized by a dense coat, a tail curved tightly over the back, a wedge-shaped head, and erect, pointed ears ('spitz' means 'pointed' in ancient German). ")},
        {Breed.bulldog,                     new BreedInfo("Kind but courageous, friendly but dignified, the Bulldog is a thick-set, low-slung, well-muscled bruiser whose 'sourmug' face is the universal symbol of courage and tenacity. These docile, loyal companions adapt well to town or country. ")},
        {Breed.bulldog_boston,              new BreedInfo("Intelligent, fast at picking up cues, and people-oriented, Boston Bulldogs make great pets. They do not require lots of exercise, although they do have a playful nature and a naturally athletic build, and love getting involved in all family's activities, actively engaging in different games. This is a generally healthy crossbreed, without the common breathing problems often associated with Bulldogs.")},
        {Breed.bulldog_english,             new BreedInfo("The English bulldog has a sweet, gentle disposition. Dependable and predictable, the bulldog is a wonderful family pet and loving to most children. People-oriented as a breed, they actively solicit human attention.\n However, they have retained the courage that was originally bred into them for bull baiting, so they make fine watchdogs. Although they generally get along well with other family pets, English bulldogs can be aggressive to unfamiliar dogs.")},
        {Breed.bulldog_french,              new BreedInfo("The one-of-a-kind French Bulldog, with his large bat ears and even disposition, is one of the world's most popular small-dog breeds, especially among city dwellers. The Frenchie is playful, alert, adaptable, and completely irresistible. The French Bulldog resembles a Bulldog in miniature, except for the large, erect 'bat ears' that are the breed's trademark feature. The head is large and square, with heavy wrinkles rolled above the extremely short nose. ")},
        {Breed.bullterrier,                 new BreedInfo("Among the most comical and mischievous citizens of dogdom, the Bull Terrier is playful and endearing, sometimes stubborn, but always devoted. These unique 'eggheads' are exuberant, muscular companions who thrive on affection and exercise. Bull Terriers are robust, big-boned terriers who move with a jaunty stride suggesting agility and power. The breed's hallmark is a long, egg-shaped head with erect and pointed ears, and small, triangular eyes that glisten with good humor. ")},
        {Breed.bullterrier_staffordshire,   new BreedInfo("From his brawling past, the muscular but agile Staffordshire Bull Terrier retains the traits of courage and tenacity. Happily, good breeding transformed this former gladiator into a mild, playful companion with a special feel for kids.")},
        {Breed.cattledog_australian,        new BreedInfo("The compact but muscular Australian Cattle Dog, also called Blue Heeler or Queensland Heeler, is related to Australia's famous wild dog, the Dingo. These resilient herders are intelligent enough to routinely outsmart their owners. Standing between 17 to 20 inches at the shoulder, the Australian Cattle Dog is a sturdy, hard-muscled herder of strength and agility. The ACD is born with a white coat that turns blue-gray or red. ")},
        {Breed.chihuahua,                   new BreedInfo("The Chihuahua is a tiny dog with a huge personality. A national symbol of Mexico, these alert and amusing 'purse dogs' stand among the oldest breeds of the Americas, with a lineage going back to the ancient kingdoms of pre-Columbian times. The Chihuahua is a balanced, graceful dog of terrier-like demeanor, weighing no more than 6 pounds. The rounded 'apple' head is a breed hallmark. The erect ears and full, luminous eyes are acutely expressive.")},
        {Breed.chow,                        new BreedInfo("The Chow Chow, an all-purpose dog of ancient China, presents the picture of a muscular, deep-chested aristocrat with an air of inscrutable timelessness. Dignified, serious-minded, and aloof, the Chow Chow is a breed of unique delights. Chows are powerful, compactly built dogs standing as high as 20 inches at the shoulder. Their distinctive traits include a lion's-mane ruff around the head and shoulders; a blue-black tongue; deep-set almond eyes that add to a scowling, snobbish expression; and a stiff-legged gait.")},
        {Breed.clumber,                     new BreedInfo("A dignified and mellow hunting companion of kings, the Clumber Spaniel is the largest of the AKC flushing spaniels. For those who can handle some shedding and drooling, the amiable Clumber is an amusing best friend and a gentlemanly housemate. Clumber Spaniels are powerful bird dogs of heavy bone, built long and low, with a massive head. They stand 17 to 20 inches; a small female might be 55 pounds, and a large male could go 85 pounds. Built to push through thick cover in the field, Clumber movement is nonetheless free and easy. The dense coat is primarily white, with sparse lemon or orange markings.")},
        {Breed.cockapoo,                    new BreedInfo("Cockapoos are friendly and affectionate little comedians with a sweet temperament and a zest for life.\nThe oldest of the designer dog breeds, cockapoos are not a true breed but, rather, a cross between the American cocker spaniel and the poodle. This offspring of a purebred cocker spaniel and a purebred poodle is also known as a cockapoodle, cockerpoo and cock-a-poo.")},
        {Breed.collie,                      new BreedInfo("The collie is a large- to medium-sized dog, with the male being quite a bit larger than the female. The ranges for the breed are 22 to 26 inches in height and 50 to 75 pounds (23 to 34 kilograms) in weight. Collies are fairly square dogs, with an expressive eye and a long muzzle. Ideally, the ears tip over at the top, although some dogs have ears that stay pricked. ")},
        {Breed.collie_border,               new BreedInfo("Border collies are active, working dogs best suited to country living. If confined without activity and company, these dogs can become unhappy and destructive. The breed is highly intelligent, learns quickly and responds well to praise.\nBecause of their herding instincts, they are protective of their family and territory and make excellent watchdogs. They will look out for the family kids. Although they get along well with children and other pets they are raised with, they can be reserved and sometimes snappish with strangers, nipping at the heels the same way they would nip at sheep if herding.")},
        {Breed.coonhound,                   new BreedInfo("A loyal, passionate breed, the black and tan coonhound is generally outgoing and friendly, although some may be reserved with strangers.\nThis large, powerful working dog has long ears that droop downward and a strong, tapered tail.")},
        {Breed.corgi,                       new BreedInfo("Known for their quick intelligence and forceful will, Pembroke Welsh corgis are active, hardy and want to be part of the family. Regular exercise is a must.\n Pembroke Welsh corgis are immediately identifiable by their short stature, prick ears and foxy face. ")},
        {Breed.corgi_cardigan,              new BreedInfo("Laid back and reserved with strangers, the Cardigan Welsh corgi, also called the Cardi, is fun-loving once it opens up. Daily exercise is needed and a firm but patient hand is often needed in training.\nThe Cardigan Welsh corgi is slightly larger than the Pembroke Welsh corgi, both in height and length.")},
        {Breed.cotondetulear,               new BreedInfo("The Coton de Tulear, 'Royal Dog of Madagascar,' is a bright, happy-go-lucky companion dog whose favorite activities include clowning, cavorting, and following their special human around the house. The Coton is small but robustly sturdy.")},
        {Breed.dachshund,                   new BreedInfo("The dachshund is a loyal companion and good with children, but because of its long back, dachshunds are prone to disk problems. Therefore this dog is not a good choice for anyone with many steps in the home.\nAll three varieties of dachshunds — the smooth-, wire- and long-coated — are found in two sizes called standard and miniature. ")},
        {Breed.dalmatian,                   new BreedInfo("Loyal, playful and intelligent, Dalmatians thrive on human companionship. They also need vigorous exercise to dispel boundless energy.\nWhen Dalmatians are born, they are completely white. The spots develop about two weeks later.")},
        {Breed.dane,                        new BreedInfo("In spite of the size, Great Danes are considered gentle giants, are moderately playful and good with children. However, an owner must be willing to accommodate the dog's great size in regard to space and feeding, which can be costly.\n Great Danes are huge, powerful and elegant dogs. Males can reach 32 inches tall and weigh anywhere from about 100 to 120 pounds, while females may be 30 inches tall and weigh about 100 to 120 pounds (45 to 59 kilograms). ")},
        {Breed.deerhound_scottish,          new BreedInfo("Friendly and sensitive, deerhounds are content to lounge most of the day. However, their running heritage demands that they get exercise vigorously once a day. Like any large dogs, they need a roomy space and plenty of food.\n The Scottish deerhound is best described as a large greyhound cloaked in a wiry coat. The breed has the typical greyhound family traits of long, slender legs, relatively narrow body, deep chest, tucked abdomen, arched loin and long tail.")},
        {Breed.dhole,                       new BreedInfo("The dhole is a canine of average size. It is different from other dog family members with its thicker muzzle, one fewer molar tooth in its lower jaw on each side, and extra teats. Its fur is thick and dense, with the color ranging from pale golden yellow to dark reddish-brown to grayish brown. The dhole’s underparts, such as its throat, chest, belly, the insides of its legs, and its paws, are paler or white. Its eyes are amber-colored.")},
        {Breed.dingo,                       new BreedInfo("The Dingo is a wild dog, found primarily in Australia. As compared with domestic dogs, the dingo has longer canines and a longer, tapered muzzle. The body shape of this dog is quite lean and the tail is bushy. Dingo has also pricked ears, which help the animal to hear well. The color of their body usually ranges from sandy-yellow to red ginger, though some individuals can be white, black, or black-tan.")},
        {Breed.doberman,                    new BreedInfo("Doberman pinschers are powerful, energetic dogs that need plenty of exercise. If not exercised, they are likely to become irritable or even aggressive. Careful socialization and obedience training from a young age are essential.\n Males are about 27 or 28 inches tall and weigh about 70 pounds (32 kilograms), while females are an inch or two shorter and weigh about 60 to 65 pounds (27 to 29 kilograms). ")},
        {Breed.elkhound,                    new BreedInfo("The high energy Norwegian elkhound needs plenty of strenuous exercise if it is to thrive. This intelligent, independent yet affectionate dog does best in a family with well-behaved older children or no children at all.\n The Norwegian Elkhound is a medium-sized, hardy and squarely built dog designed to withstand cold weather and hunt for days at a time.")},
        {Breed.entlebucher,                 new BreedInfo("The Entlebucher Mountain Dog, tricolor 'Laughing Dog' of the Swiss Alps, is a rugged and determined mover of cattle. These spirited, energetic workers and athletes are independent problem solvers and are happiest with a job to perform. Entlebucher (ENT-leh-boo-cur) Mountain Dogs are muscular, long-backed cattle dogs standing from 16 to 21 inches at the shoulder. ")},
        {Breed.eskimo,                      new BreedInfo("A classic family dog, the American Eskimo makes an excellent watchdog but is prone to excessive barking.\nThe American Eskimo is a family dog. Eskies are very loyal and need to be around their owners. They are highly intelligent, but can be stubborn. They make good watchdogs, but are prone to excessive barking.")},
        {Breed.finnish_lapphund,            new BreedInfo("The weatherproof Finnish Lapphund is a tough and substantial reindeer herder from north of the Arctic Circle. This remarkably empathetic breed is among the friendliest of all dogs, once he's satisfied that you aren't a reindeer rustler. Finnish Lapphunds, with their luscious coat, sweet spitz-like face, and profusely coated tail that curves over the back, are instantly recognizable as Nordic dogs. Lappies stand about 20 inches at the shoulder and are surprisingly muscular and substantial for their inches")},
        {Breed.frise_bichon,                new BreedInfo("A playful, yet gentle dog, the bichon frise doesn’t need much room to romp and is suitable for apartment living. The breed is not known for barking.\nBichons are similar to poodles in terms of their powder-puff coat, which consists of a silky but curly outer coat and soft undercoat. They are white, white and buff, cream, apricot or gray.")},
        {Breed.germanshepherd,              new BreedInfo("Smart and easily trained, the ever-popular German shepherd is quite active and likes to have something to do. Therefore, they need ample daily exercise daily; otherwise, they become mischievous or high-strung.\nGerman shepherd dogs get along well with children and other pets if raised with them, but in keeping with their guarding instincts, they tend to be leery of strangers.")},
        {Breed.greyhound,                   new BreedInfo("The greyhound is intelligent, gentle with a quiet disposition, and in spite of its great athletic ability, is content to spend most of the day sleeping. Short on endurance it requires less exercise time than most dogs.\nThe greyhound is built for speed with a streamlined, muscular body. The neck and head are long. Their characteristic rose ears are usually folded flat against the neck when the dog is relaxed, but prick forward and may even stand somewhat erect when the greyhound is at attention. The loin is slightly arched, the chest is deep, and the waist is narrow, giving the dog a distinctive appearance.")},
        {Breed.greyhound_italian,           new BreedInfo("A gentle indoor dog that requires minimal exercise, the Italian greyhound is affable, but desires affection.\nThe Italian greyhound is truly a greyhound in miniature, with supreme elegance and grace. The height at the withers is 13 to 15 inches, and the weight is 7-14 pounds. The slender, muscular body, accentuated by the curved back, deep chest, and lean, well-muscled legs, produces a sinewy outline. The slender tail tapers to a curved end that is carried low. The head is long and narrow, the muzzle fine, and the ears pliant and delicate.")},
        {Breed.groenendael,                 new BreedInfo("With his solid black coat, athletic build, and bright temperament, the Groenendael sets himself apart from other breeds. Developed for herding in Belgium, this breed of dog is very smart and trainable, but they do require an experienced dog owner who will maintain a firm and consistent hand in training. The Groenendael is a natural protective and territorial breed, but they can do well with children when properly socialized and they make good family pets as long as their exercise requirements are met.")},
        {Breed.havanese,                    new BreedInfo("Active, intelligent, happy and trainable, the Havanese breed is ideal for the guardian who wants a small dog that can be content with frequent walks and games of fetch.\nHavanese are small dogs weighing seven to 13 pounds. The height ranges from 8 1/2 to 11 1/2 inches at the shoulder. The body is longer than tall; they have drop ears and a tail that curls over the back. Havanese generally mature at 1 year of age, although they reach their full size around 6 to 8 months.")},
        {Breed.hound,                       new BreedInfo("Most hounds share the common ancestral trait of being used for hunting. Some use acute scenting powers to follow a trail. Others demonstrate a phenomenal gift of stamina as they relentlessly run down quarry. Beyond this, however, generalizations about hounds are hard to come by, since the Group encompasses quite a diverse lot.")},
        {Breed.hound_afghan,                new BreedInfo("An independent, strong-willed dog, the Afghan can be downright standoffish, but also quiet and clownish when the mood strikes.\nThe male Afghan hound stands about 27 inches tall, the female about 25 inches. Afghans generally weigh between 50 and 60 pounds (23 to 27 kilograms).")},
        {Breed.hound_basset,                new BreedInfo("The basset hound is a friendly, easygoing dog. Originally hunting in packs, they tend to be good with other dogs and other pets in general. Bassets are people oriented and get along well with children. Fairly smart dogs, bassets are not easy to train as they are somewhat stubborn.\nDespite its low height of under 15 inches, the basset hound is a medium to large dog, weighing in at anywhere from 40 pounds for a small female to 80 pounds for a large male (18 to 36 kilograms).")},
        {Breed.hound_blood,                 new BreedInfo("Patient and mild-mannered, the bloodhound can also exhibit deep determination and independence. This breed can be a great companion but also a challenge.\nThe bloodhound is a large dog with long droopy ears and wrinkled skin, especially on the face.")},
        {Breed.hound_english,               new BreedInfo("An active, athletic and energetic dog, the English foxhound needs a great deal of exercise to thrive and is best suited for the countryside.\nThe English foxhound is a stouter dog than his American foxhound cousin. Males are about 22 to 25 inches tall, and females average an inch shorter. Weights range between 6555 and 7075 pounds (259 to 342 kilograms).")},
        {Breed.hound_ibizan,                new BreedInfo("Known for being gentle, lacking of 'street' smarts and wanting to be pampered, the Ibizan hound would instantly trade a soft bed for a chance to run and hunt.\nThe Ibizan (pronounced ee-BEE-than) hound bears an uncanny resemblance to the Egyptian god Anubis. One of the sight hound family, the breed is built on general greyhound lines, with long slender legs, a relatively narrow body, a slightly arched loin, narrow waist and long tail. With the exception of its large ears, the Ibizan hound is a somewhat understated version of the greyhound.")},
        {Breed.hound_plott,                 new BreedInfo("The Plott, a hound with a curious name and a unique history, is a rugged, relentless hunting dog who is a mellow gentleman at home but fearless, implacable, and bold at work. This eye-catching scenthound is North Carolina's state dog. The hound with the curious name (we'll get to that) and unique history (we'll get to that, too) is a streamlined, long-tailed, light-footed hunter standing as high as 25 inches at the shoulder.")},
        {Breed.hound_walker,                new BreedInfo("The treeing walker coonhound is a medium-large hound dog breed native to the United States that has a short, low-maintenance coat and long, floppy ears. This hound dog generally makes a loving and loyal companion, and, when it gets enough daily physical activity, it can be quite mellow in the house. ")},
        {Breed.husky,                       new BreedInfo("The classic northern dogs, Siberian huskies are friendly and intelligent but somewhat independent and stubborn. They thrive on human company, but need firm, gentle training from puppyhood.\nThe Siberian husky is a medium-sized dog, slightly longer than tall. Height ranges from 20 to 23 1/2 inches and weight from 35 to 60 pounds.")},
        {Breed.keeshond,                    new BreedInfo("The playful, affectionate nature with minimal training needed makes the Keeshond an ideal pet. Because of the Keeshond’s thick coat a hot, humid climate is not recommended.\nThe Keeshond (pronounced KAYZ-hawnd) is a double-coated breed. This coat consists of a woolly undercoat and a longer guard coat. The undercoat is a pale gray or cream color and the outer guard hairs are a mixture of gray and black with black tips. Twice a year, Keeshonden 'blow' or shed their undercoats completely. This intense shedding period can last up to three weeks. Keeshonden appear larger than they really are because of their full, thick coat.")},
        {Breed.kelpie,                      new BreedInfo("The Australian Kelpie is a lithe, active dog, capable of untiring work. He is extremely intelligent, alert, and eager with unlimited energy.\nAs a herding dog, the Australian Kelpie is intensely loyal and devoted to duty. He has a natural instinct and aptitude for working in sheep, whether it be in open fields or enclosed yards. This breed originated from Collie type dogs imported from Scotland, but was developed to withstand the harsh heat and dry conditions of the vast open spaces of Australia.")},
        {Breed.komondor,                    new BreedInfo("The Komondor is a loving dog who needs little exercise and likes to keep its human companions in sight, often following them. Intelligent with a keen instinct for protection, the Komondor's independent thought process can make this breed ill-suited to many.\nKomondorok (Hungarian plural komondorok) have a distinctively imposing presence, if not for their large stature and heavy musculature, then for their most striking feature — a tasseled white coat consisting of tight cords similar to Rastafarian dreadlocks.")},
        {Breed.kuvasz,                      new BreedInfo("Known for being gentle, protective and easy to care for, the Kuvasz can be independent and aggressive and therefore needs firmness during the training and socialization period.\nKuvasz are large dogs, slightly longer than tall, so they are rectangular in body outline. They are not heavy, bulky dogs, but rather give the appearance of agility as well as strength. The ears are folded forward and do not stand erect, while the tail plume curves up gracefully when the dog is alert. The head is not coarse but somewhat refined.")},
        {Breed.labradoodle,                 new BreedInfo("The Labradoodle is a mixed breed with a Labrador Retriever and Standard Poodle parent. In this guide we will help you to decide whether a Labradoodle puppy would be a good fit for your lifestyle. And give you the tools you need to raise your Labradoodle to become a happy, well behaved member of the family.")},
        {Breed.labrador,                    new BreedInfo("The Labrador possesses numerous endearing traits — intelligence, easy to train and being an excellent family companion. They require moderate exercise, but if not provided, or if left alone, Labs can be destructive.\nLabrador retrievers are sturdy, solid dogs. They are almost square in appearance, with a strong body and sturdy legs. The maximum height for a male is 24 inches, which puts them in the medium-size dog category, but their sturdy build can make them seem much larger. Weights range from 85 pounds for a large male to 55 pounds for a smaller female. Field line bred dogs are often taller and somewhat thinner in build.")},
        {Breed.leonberg,                    new BreedInfo("Calm, quiet but stubborn, the Leonberger needs significant interaction with people. It is an ideal breed for a guardian who wants a large, active dog that can be taken hiking, backpacking and swimming.")},
        {Breed.lhasa,                       new BreedInfo("Considered 'easy keepers' affectionate and a good companion, the Lhasa Apso was bred as a guard dog and therefore can be aloof, stubborn and demonstrate a sharp, loud bark.\nLhasa Apsos are fairly small dogs, ranging in height from 9 to 11 inches and weigh from 13 to 18 pounds (six to eight kilograms).")},
        {Breed.malamute,                    new BreedInfo("An immensely strong, heavy-duty worker of spitz type, the Alaskan Malamute is an affectionate, loyal, and playful but dignified dog recognizable by his well-furred plumed tail carried over the back, erect ears, and substantial bone. The Alaskan Malamute stands 23 to 25 inches at the shoulder and weighs 75 to 85 pounds.")},
        {Breed.malinois,                    new BreedInfo("A strong, rugged dog, the Belgian Malinois exhibits a wide range of temperament and aggressiveness. This breed is not suitable for households with small, erratic children.\nThe Belgian Malinois is an elegant, well-proportioned, natural, medium-sized, square dog.")},
        {Breed.maltese,                     new BreedInfo("Highly suitable for indoor living and small areas, the diminutive Maltese is gentle, responsive and intelligent. It can be a fickle eater and difficult to housebreak.\nThe Maltese is a diminutive dog weighing from four to six pounds (two to three kilograms).")},
        {Breed.mastiff,                     new BreedInfo("Known to be good-natured, loving and a good companion to older children, the imposing mastiff must be exposed to as many to new people and situations as possible as a puppy.")},
        {Breed.mastiff_bull,                new BreedInfo("Fearless at work, docile at home, the Bullmastiff is a large, muscular guarder who pursued and held poachers in Merry Old England'¿merry, we suppose, for everyone but poachers. Bullmastiffs are the result of Bulldog and Mastiff crosses. The Bullmastiff isn't quite as large as his close cousin the Mastiff.")},
        {Breed.mastiff_english,             new BreedInfo("The colossal Mastiff belongs to a canine clan as ancient as civilization itself. A massive, heavy-boned dog of courage and prodigious strength, the Mastiff is docile and dignified but also a formidable protector of those they hold dear. For the uninitiated, a face-to-face encounter with these black-masked giants can be startling.")},
        {Breed.mastiff_tibetan,             new BreedInfo("Watchful, aloof, imposing, and intimidating: The ancient Tibetan Mastiff is the guardian dog supreme. These densely coated giants are mellow and calm around the house, sweetly devoted to family, and aloof and territorial with strangers. Coming face to face with this ancient behemoth, an intruder up to no good will likely move on to easier pickings.")},
        {Breed.mexicanhairless,             new BreedInfo("The Xoloitzcuintli combines grace and strength equally and is moderate in all aspects of their appearance. All three sizes are slightly longer than tall, and they are lean and sturdy with medium build. Their gait is effortless with good reach and drive. Their coated variety has a short, flat coat. The hairless variety has no coat or almost no coat, often with short, coarse hair on the top of their head, their feet, and the last third of their tail.")},
        {Breed.mix,                         new BreedInfo("Every dog combined")},
        {Breed.mountain,                    new BreedInfo("Big, powerful, and built for hard work, the Mountain Dog is also strikingly beautiful and blessed with a sweet, affectionate nature.")},
        {Breed.mountain_bernese,            new BreedInfo("An alert, good-natured breed, the Bernese mountain dog is eager to please and will welcome jobs to do as a family pet.\nThe Bernese mountain dog is a large dog with a beautiful tri-colored coat.")},
        {Breed.mountain_swiss,              new BreedInfo("The Greater Swiss Mountain Dog is a large, immensely strong worker famous for a dense coat of striking black, red, and white markings. Dependable and faithful Swissies earned their feed as herders, drafters, and all-around pasture dogs.")},
        {Breed.newfoundland,                new BreedInfo("Despite the Newfoundland's size, this friendly and intelligent dog is rather docile and can happily adjust to a household. However, it does need yard space for exercise and ideally, access to water.\nThe Newfoundland is a large, heavy-coated dog.")},
        {Breed.otterhound,                  new BreedInfo("Big, boisterous, and affectionate, the Otterhound was bred in medieval England for the now-outlawed activity of otter hunting. This scarce breed is known for his dense shaggy coat, webbed feet, acute sense of smell, and affinity for swimming. These big, bouncy hounds were ideally suited for otter hunting.")},
        {Breed.ovcharka_caucasian,          new BreedInfo("Originating in the Caucusus region near the border between Europe and Asia, the Caucasian Ovcharka has been used for many centuries to guard livestock from predators. Powerfully built and intensely protective, they are one of the only breeds known to fight and kill wolves. Historically they were also used for property protection, and as hunting dogs. The name Ovcharka means shepherd or sheep dog in Russian, but this can be misleading. This breed does not herd as other shepherds do, but stands alert and ready to defend the flock as they move across the landscape.")},
        {Breed.papillon,                    new BreedInfo("The quick, curious Papillon is a toy dog of singular beauty and upbeat athleticism. Despite his refined appearance, the Pap is truly a 'doggy dog' blessed with a hardy constitution. Papillon fanciers describe their breed as happy, alert, and friendly. A tiny dog, measuring 8 to 11 inches at the shoulder, you can still spot a Papillon a block away thanks to the large, wing-shaped ears that give the breed its name ('papillon' is French for 'butterfly')")},
        {Breed.pekinese,                    new BreedInfo("Needing limited exercise and minimal food to maintain health, the Pekingese is an easy-to-care-for breed. However, it does thrive with attention and enjoys being a lapdog.")},
        {Breed.pembroke,                    new BreedInfo("Known for their quick intelligence and forceful will, Pembroke Welsh corgis are active, hardy and want to be part of the family. Regular exercise is a must. ")},
        {Breed.pinscher_miniature,          new BreedInfo("Active, curious and entertaining, the Miniature Pinscher is not for the peaceful household. Most Miniature Pinschers burn much of their energy playing indoors and do not require large spaces to exercise.\nNo physical description can ever capture the essence of this breed.")},
        {Breed.pitbull,                     new BreedInfo("Most pit bulls are fun, gentle companions and patient with family members. As with all breeds, there are exceptions.\nStrong and stocky, yet light on his feet, the pit bull may pack more muscles per pound of body weight than any other breed.")},
        {Breed.pointer,                     new BreedInfo("An independent, stubborn and strong-willed dog, the English Pointer is considered a dog best suited for the country because its need for exercise and boundless energy.")},
        {Breed.pointer_german,              new BreedInfo("The German shorthaired pointer is an excellent family dog, but is not content to sit around. Playful and intelligent, this dog needs ample daily exercise and access to a fairly sized yard. ")},
        {Breed.pointer_germanlonghair,      new BreedInfo("Needing vigorous daily exercise, the German wirehaired pointer is not suited for apartment living or small homes. The dog is considered even-tempered and loyal to its family and interacts well with children.")},
        {Breed.pomeranian,                  new BreedInfo("Perky and friendly, Pomeranians, even though small, need regular exercise and thrive on training. They are intelligent, but sometimes do not realize they are small and will confront larger dogs. ")},
        {Breed.poodle,                      new BreedInfo("Poodles are notorious for their intelligence and ease of training. They are lively, active, fun-loving and family dogs with a sense of the ridiculous. ")},
        {Breed.poodle_medium,               new BreedInfo("Poodles are notorious for their intelligence and ease of training. They are lively, active, fun-loving and family dogs with a sense of the ridiculous. ")},
        {Breed.poodle_miniature,            new BreedInfo("Poodles are notorious for their intelligence and ease of training. They are lively, active, fun-loving and family dogs with a sense of the ridiculous. ")},
        {Breed.poodle_standard,             new BreedInfo("Poodles are notorious for their intelligence and ease of training. They are lively, active, fun-loving and family dogs with a sense of the ridiculous. ")},
        {Breed.poodle_toy,                  new BreedInfo("Poodles are notorious for their intelligence and ease of training. They are lively, active, fun-loving and family dogs with a sense of the ridiculous. ")},
        {Breed.pug,                         new BreedInfo("Serious with a laid-back attitude, pugs are robust and easy to care for but it is notable they do not do well in hot, humid weather and must be observed carefully for heatstroke. ")},
        {Breed.puggle,                      new BreedInfo("The cross-bred offspring of a beagle and a pug, the puggle is an adorable designer breed with an enthusiastic and loving disposition.\nThe wrinkles and shortened nose of a pug combined with the beagle's more elongated features and floppy ears cause puggles, and puggle puppies, to resemble a smaller version of a mastiff.")},
        {Breed.pyrenees,                    new BreedInfo("If a family leads a placid life, the Great Pyrenees makes a great pet. The dog is calm, devoted and well-mannered, but an owner must have patience during training because the dog tends to be independent and stubborn.")},
        {Breed.redbone,                     new BreedInfo("The streamlined Redbone Coonhound, an American original, is even-tempered, mellow, and kindly at home but a tiger on the trail. Vigorous activities like hunting and swimming between long periods of rest is the rhythm of coonhound life. Redbones are medium-to-large hound dogs whose muscles undulate beneath a sleek and stunning red coat. ")},
        {Breed.retriever,                   new BreedInfo("Originally bred to help hunters, retrievers were tasked with finding birds or other game and bringing them back undamaged. For this sort of job, the dog needed a “soft,” gentle mouth, where he would carefully carry the prey without damaging it.")},
        {Breed.retriever_chesapeake,        new BreedInfo("Chesapeake Bay retrievers are not as gregarious as most other retriever breeds, but generally like children. They need plenty of exercise. Differing opinions exist on house training.")},
        {Breed.retriever_curly,             new BreedInfo("Curly-coated retrievers are even-tempered, intelligent, affectionate and highly energetic. They prefer to spend time with their family as opposed to being alone outdoors; however, they require ample exercise. ")},
        {Breed.retriever_flatcoated,        new BreedInfo("The flat-coated retriever is sociable and friendly to all and loves to be with the family. Its personality has been referred to as 'forever puppy' because of its slow maturing process.")},
        {Breed.retriever_golden,            new BreedInfo("Because golden retrievers are easy to please, they respond positively to obedience training. They complement this trait by being playful, affectionate and even-tempered.")},
        {Breed.ridgeback_rhodesian,         new BreedInfo("Although it may give the impression of a big, lazy hound, the Rhodesian ridgeback has won admirers for its innate qualities. It is gregarious with a quiet, gentle temperament and is an excellent companion. ")},
        {Breed.rottweiler,                  new BreedInfo("Not recommended for first-time owners, the rottweiler needs extensive and continuous socialization to be a good family companion. However, this intelligent, confident dog is easy to keep in spite of the size. ")},
        {Breed.saluki,                      new BreedInfo("Known to be content to lounge for hours, the saluki still needs daily exercise. The saluki, a devoted but not a demonstrative dog, is gentle with children and relishes sitting by your side. ")},
        {Breed.samoyed,                     new BreedInfo("Personable and intelligent, Samoyeds thrive on human companionship and do not do well when left alone for extended periods. They are an easy-to-keep breed, thriving on smaller amounts of high quality food. ")},
        {Breed.schipperke,                  new BreedInfo("Schipperkes are active, intelligent and curious dogs and have stubborn tendencies. They are ideal for owners who want a small-sized, active dog that does not require a large yard. ")},
        {Breed.schnauzer,                   new BreedInfo("Known to be highly intelligent, strong-willed and high-spirited, the standard schnauzer is easily trained and loyal. Their intelligence can be a blessing or curse in disguise. ")},
        {Breed.schnauzer_giant,             new BreedInfo("To assimilate to a family, early and extensive training is necessary for the highly intelligent and loyal giant schnauzer. His intelligence can be a blessing or a curse.")},
        {Breed.schnauzer_miniature,         new BreedInfo("Quick learners and adaptable, Miniature Schnauzers can be just as happy living in a city apartment or in the country. These spunky dogs are socialable and need to be included in family activities.")},
        {Breed.setter,                      new BreedInfo("The Setter is a medium-sized sporting dog of sweet temper and show-stopping good looks.")},
        {Breed.setter_english,              new BreedInfo("Considered an alert dog and a protector of the family, the English setter is quite friendly, gentle and mild-mannered, but needs regular interaction with people and brisk daily walks.")},
        {Breed.setter_gordon,               new BreedInfo("The Gordon Setter, the black avenger of the Highlands, is a substantial bird dog named for a Scottish aristocrat. Athletic and outdoorsy, Gordons are bold, confident, and resolute in the field, and sweetly affectionate by the fireside")},
        {Breed.setter_irish,                new BreedInfo("Bred for hunting, the Irish setter loves to run and needs considerable exercise. Irish setters are good-sized dogs, ranging from 25 to 27 inches in height and 60 to 70 pounds in weight.")},
        {Breed.sharpei,                     new BreedInfo("As puppies, this breed's wrinkly skin is reminiscent of the chubby folds of a human baby. As adults, the shar-pei dog breed fills out but never grows completely into their skin, retaining their signature wrinkles around the head, neck and shoulders. Intelligent, loyal and fiercely protective, shar-peis make good guardian dogs, but also possess a calm demeanor that makes them excellent family companions.")},
        {Breed.sheepdog,                    new BreedInfo("An obedient, multi-talented breed, a sheepdog can be difficult to control if the guardian is inexperienced.")},
        {Breed.sheepdog_english,            new BreedInfo("Smart, but independent with a sense of humor, Old English sheepdogs require a fair amount of exercise; plus early training and socialization is a must. ")},
        {Breed.sheepdog_shetland,           new BreedInfo("Shetland sheepdogs or Shelties are known for their gentle and sweet personality. This popular family pet likes to keep busy, functions well in small homes and is content to lie around alone all day, but still needs to be exercised. ")},
        {Breed.shiba,                       new BreedInfo("An ancient Japanese breed, the Shiba Inu is a little but well-muscled dog once employed as a hunter. Today, the spirited, good-natured Shiba is the most popular companion dog in Japan.")},
        {Breed.shihtzu,                     new BreedInfo("hat face! Those big dark eyes looking up at you with that sweet expression! It's no surprise that Shih Tzu owners have been so delighted with this little 'Lion Dog' for a thousand years. Where Shih Tzu go, giggles and mischief follow. Shi Tsu (pronounced in the West 'sheed-zoo' or 'sheet-su'; the Chinese say 'sher-zer'), weighing between 9 to 16 pounds, and standing between 8 and 11 inches, are surprisingly solid for dogs their size.")},
        {Breed.spaniel,                     new BreedInfo("A spaniel is a type of gun dog. Spaniels were especially bred to flush game out of denser brush. By the late 17th century, spaniels had been specialized into water and land breeds.")},
        {Breed.spaniel_blenheim,            new BreedInfo("The Cavalier King Charles Spaniel Blenheim is amongst one of many oldest toy breeds boasting an illustrious historical past that may be traced again to a number of centuries. In this article, I am going to talk about Cavalier King Charles Spaniel Blenheim puppy, spot, markings, color, temperament, etc.")},
        {Breed.spaniel_brittany,            new BreedInfo("Sportsmen on both sides of the Atlantic cherish the agile, energetic Brittany as a stylish and versatile gundog. Bright and eager at home, and tireless afield, Brittanys require a lot of exercises, preferably with their favorite humans. Brittanys are smaller than setters but leggier than spaniels, standing about 20 inches at the shoulder.")},
        {Breed.spaniel_cocker,              new BreedInfo("The merry and frolicsome Cocker Spaniel, with his big, dreamy eyes and impish personality, is one of the world's best-loved breeds. They were developed as hunting dogs, but Cockers gained their wide popularity as all-around companions.")},
        {Breed.spaniel_irish,               new BreedInfo("The tallest of the AKC's spaniels, the Irish Water Spaniel is instantly recognizable by its crisply curled coat and tapering 'rat tail.' Among the champion swimmers of dogdom, the alert and inquisitive IWS is hardworking and brave in the field, and playfully affectionate at home.")},
        {Breed.spaniel_japanese,            new BreedInfo("Japanese spaniel, additionally known as Japanese Chin, breed of toy canine that originated in China and was launched to Japan, the place it was saved by royalty.\n The breed grew to become identified within the West when Commodore Matthew Perry returned from Japan in 1853 with a number of canines that had been offered to him. ")},
        {Breed.spaniel_sussex,              new BreedInfo("'Placid, affectionate, even-tempered, true-blue, loyal' all are words used to describe the Sussex Spaniel, a slow-but-steady hunter, and congenial housedog. His frowning expression is delightfully at odds with a typically cheerful nature.")},
        {Breed.spaniel_welsh,               new BreedInfo("he Welsh Springer Spaniel is a vigorous, medium-sized bird dog of happy disposition, known for versatility in the field, companionability at home, and dashing good looks anywhere.")},
        {Breed.springer,                    new BreedInfo("Renowned for devotion and loyalty, the Welsh springer spaniel is energetic, but possesses a calm temperament. This dog can be reserved toward strangers. ")},
        {Breed.springer_english,            new BreedInfo("A hardy, energetic and fairly intelligent dog, the English springer spaniel is outgoing and friendly, but still should have socialization and training from the beginning.")},
        {Breed.stbernard,                   new BreedInfo("Known to be loving, gentle and tolerant in spite of its size, Saint Bernards are a good with families with well-behaved children. In addition, they are eager to please, making training easier. ")},
        {Breed.terrier,                     new BreedInfo("Feisty and energetic are two of the primary traits that come to mind for those who have experience with Terriers. In fact, many describe their distinct personalities as 'eager for a spirited argument.'")},
        {Breed.terrier_american,            new BreedInfo("A fairly new breed, the American hairless terrier closely resembles its rat terrier ancestor in all ways but one — the coat. Despite its name, the American hairless dog breed comes in coatless and coated varieties, with the latter possessing a very short, shiny coat. Bright, playful and energetic, the coatless American hairless is an excellent match for people with allergies.")},
        {Breed.terrier_australian,          new BreedInfo("The diminutive Australian Terrier is plucky, spirited, and smart. How did they fit so much dog into such a bitty package? Upbeat and lively, the self-assured Aussie approaches life with plenty of the old-time terrier curiosity and grit. Australian Terriers are small but sturdy, self-confident terriers known for a longish torso, distinctive coat furnishings around the neck and forequarters, and a topknot of soft, silky hair that contrasts in texture with an otherwise harsh coat.")},
        {Breed.terrier_bedlington,          new BreedInfo("Graceful terriers in sheep's clothing, Bedlington Terriers, named for the English mining shire where they were first bred, are genial housemates, alert watchdogs, versatile athletes, and irresistibly cuddly TV-time companions.")},
        {Breed.terrier_border,              new BreedInfo("Admirers of the upbeat and agile Border Terrier cherish their breed's reputation as a tough, no-frills working terrier. These plucky, happy, and affectionate dogs are popular pets in town and country.")},
        {Breed.terrier_cairn,               new BreedInfo("Cairn Terriers are happy, busy little earthdogs originally bred to fearlessly root out foxes and other small, furred prey in the rocky Scottish countryside. Curious and alert, Cairns like having a place where they can explore and dig.")},
        {Breed.terrier_dandie,              new BreedInfo("The unique-looking Dandie Dinmont Terrier is a tough but dignified little exterminator. Sturdily built for the rigors of farm life, they will agreeably adapt to city living. Dandies are compact companions blessed with a big personality.")},
        {Breed.terrier_fox,                 new BreedInfo("The Smooth Fox Terrier, called the 'gentleman of the terrier world,' is a lively, gregarious terrier with a devil-may-care attitude, originally developed for Britain's traditional foxhunts. They are close relatives to Wire Fox Terriers")},
        {Breed.terrier_irish,               new BreedInfo("The Irish Terrier, 'Daredevil' of the Emerald Isle, is a bold, dashing, and courageous terrier of medium size. Known for his fiery red coat and a temperament to match, the Irish Terrier is stouthearted at work and tenderhearted at home. Irish Terriers are the prototype of a long-legged terrier.")},
        {Breed.terrier_kerryblue,           new BreedInfo("Among the largest of terriers, the Kerry Blue Terrier is famous for his show-stopping blue coat. Named for the Irish county of his birth, this onetime farm dog is today an alert, adaptable, and animated watchdog and family companion. Of course, we begin with the show-stopping coat that turns heads wherever Kerries go. ")},
        {Breed.terrier_lakeland,            new BreedInfo("A bold, zesty 'big dog in a small package' the Lakeland Terrier, named for the Lake District of his native England, was once a farmer's dog bred to work in packs on sheep-stealing foxes. The Lakie's coat is hard, wiry, and low-shedding.")},
        {Breed.terrier_norfolk,             new BreedInfo("Norfolk Terriers are little, cute, and loyal, and they will gladly curl up in your lap, but don't dare call them lapdogs. Norfolks, despite their toyish qualities, are genuine terriers' feisty, confident, sturdy, and game for adventure.")},
        {Breed.terrier_norwich,             new BreedInfo("Norwich Terriers are plucky little earthdogs named for their hometown in England. The old cliche 'a big dog in a small package' was coined for breeds like the Norwich, who can be oblivious to the fact that they are just 10 inches tall.")},
        {Breed.terrier_patterdale,          new BreedInfo("The Patterdale Terrier is a compact, working breed that was originally bred to hunt foxes and other vermin. While there isn’t as much need for full time hunting dogs these days, the Patterdale Terrier has proven to quite a popular bet.")},
        {Breed.terrier_russell,             new BreedInfo("The Parson Russell Terrier is a bold and clever terrier, swift enough to run with horses and fearless enough to dig in and flush a fox from his lair. Independent problem solvers, PRTs can have their own ideas on how to go about things.")},
        {Breed.terrier_scottish,            new BreedInfo("A solidly compact dog of vivid personality, the Scottish Terrier is an independent, confident companion of high spirits. Scotties have a dignified, almost-human character. Their terrier persistence has earned the breed the nickname 'the Diehard.'")},
        {Breed.terrier_sealyham,            new BreedInfo("The Sealyham Terrier is brave and spirited, but not as spiky as smaller terriers. These sturdy, outgoing companions are recognized by their 'fall' the mass of hair covering the forehead. ")},
        {Breed.terrier_silky,               new BreedInfo("The compact, glossy-coated Silky Terrier is nonetheless a true terrier of energetic high spirits. The Silky, a native of Sydney, Australia, is larger than his close cousin, the Yorkshire Terrier.")},
        {Breed.terrier_tibetan,             new BreedInfo("The Tibetan Terrier, 'Holy Dog of Tibet,' is an ancient watchdog and companion long associated with Buddhist monasteries. A profusely coated, small-to-medium-sized dog with 'snowshoe' feet, the TT is affectionate, sensitive, and clever. ")},
        {Breed.terrier_toy,                 new BreedInfo("The Manchester Terrier is named after the English city where it was first bred. Sleek, racy dogs who possess a terrier's ratting instinct and the graceful contours of coursing hounds, Manchesters are spirited, bright, and athletic. They combine the streamlined grace of a coursing hound and the instincts of a fearless rat terrier.")},
        {Breed.terrier_welsh,               new BreedInfo("They stand about 15 inches at the shoulder, a little larger than the Lakeland Terrier but much smaller than the mighty Airedale.")},
        {Breed.terrier_westhighland,        new BreedInfo("Smart, confident, and always entertaining at play, the adorable West Highland White Terrier (Westie, for short) has charmed owners for over 300 years. This diminutive but sturdy earthdog is among the most popular of the small terriers.")},
        {Breed.terrier_wheaten,             new BreedInfo("The Soft Coated Wheaten Terrier, an exuberant Irish farm dog, is happy, friendly, deeply devoted, and just stubborn enough to remind you he's a terrier. The unique wheaten coat is low-shedding but needs diligent care to avoid matting.")},
        {Breed.terrier_yorkshire,           new BreedInfo("Beneath the dainty, glossy, floor-length coat of a Yorkshire Terrier beats the heart of a feisty, old-time terrier. Yorkies earned their living as ratters in mines and mills long before they became the beribboned lapdogs of Victorian ladies.")},
        {Breed.tervuren,                    new BreedInfo("The elegant, agile Belgian Tervuren is a bright and self-assured herding dog of medium size, known to be affectionate and possessive with loved ones. Lots of hard work and challenging play is heaven for this tireless, do-it-all dog. The Belgian Tervuren is characterized by a straight and abundant coat, an elegant but muscular frame, a proudly carried head, an alert and intelligent demeanor, and an insatiable work drive.")},
        {Breed.vizsla,                      new BreedInfo("Vizslas, a friendly and intelligent dog, require a high level of physical activity and considerable interaction with people. They may suffer separation anxiety and fear of loud noises such as thunderstorms.")},
        {Breed.waterdog,                    new BreedInfo("An excellent family pet, the American water spaniel is smart, obedient and affectionate. The breed is known for barking a lot.")},
        {Breed.waterdog_spanish,            new BreedInfo("Ideal for owners who want a medium-sized, intelligent, active dog, Spanish Water Dogs require a high level of physical activity and prefer being with their guardians. ")},
        {Breed.weimaraner,                  new BreedInfo("Ideal for owners who want a large, active dog for hunting, hiking, and other outdoor activities, Weimaraners are great companions and highly intelligent, but need activities to prevent destructive behavior. ")},
        {Breed.whippet,                     new BreedInfo("Whippets are gentle, non-aggressive and enjoy human companionship. They can be an apartment dog if exercised a couple of times a day.")},
        {Breed.wolfhound,                   new BreedInfo("Once fearless big-game hunters capable of dispatching a wolf in single combat, Wolfhounds today are the most serene and agreeable of companions.")},
        {Breed.wolfhound_irish,             new BreedInfo("Irish wolfhounds are big-hearted, gentle and sensitive but their size is an important consideration. They're the size of another person and owners must plan accordingly.")},
    };
#pragma warning restore

}
